default_lang: 'en'
languages: ['en', 'es']

# default_lang: 'en'
# languages: ['en', 'ru']
page_gen:
  - data: 'amenities'
    template: 'amenity'
    dir: 'amenities'

exclude:
  - 'sitemap.json'
  - 'assets'
  
